/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ClassFormDialog: typeof import('./src/components/ClassFormDialog.vue')['default']
    copy: typeof import('./src/components/SubjectFormDialog copy.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubjectFormDialog: typeof import('./src/components/SubjectFormDialog.vue')['default']
    UserFormDialog: typeof import('./src/components/UserFormDialog.vue')['default']
  }
}
