/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/property/LoginPage': RouteRecordInfo<'/property/LoginPage', '/property/LoginPage', Record<never, never>, Record<never, never>>,
    '/property/PropertyPage': RouteRecordInfo<'/property/PropertyPage', '/property/PropertyPage', Record<never, never>, Record<never, never>>,
    '/school/ClassPage': RouteRecordInfo<'/school/ClassPage', '/school/ClassPage', Record<never, never>, Record<never, never>>,
    '/school/LoginPage': RouteRecordInfo<'/school/LoginPage', '/school/LoginPage', Record<never, never>, Record<never, never>>,
    '/school/SchedulePage': RouteRecordInfo<'/school/SchedulePage', '/school/SchedulePage', Record<never, never>, Record<never, never>>,
    '/school/SubjectPage': RouteRecordInfo<'/school/SubjectPage', '/school/SubjectPage', Record<never, never>, Record<never, never>>,
    '/UserPage': RouteRecordInfo<'/UserPage', '/UserPage', Record<never, never>, Record<never, never>>,
  }
}
